// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quiz.Data;

public partial class Answers
{
    public int Id_Answer { get; set; }

    public int fk_Question { get; set; }

    public string Description { get; set; }

    public bool IsCorrect { get; set; }

    public int Index { get; set; }

    public virtual Questions fk_QuestionNavigation { get; set; }
}