// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quiz.Data;

public partial class Questions
{
    public int Id_Question { get; set; }

    public int fk_Quiz { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Answers> Answers { get; set; } = new List<Answers>();

    public virtual Quizes fk_QuizNavigation { get; set; }
}