// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quiz.Data;

public partial class RoomQuizes
{
    public int Id_RoomQuize { get; set; }

    public int fk_Room { get; set; }

    public int fk_Quiz { get; set; }

    public virtual Quizes fk_QuizNavigation { get; set; }

    public virtual Rooms fk_RoomNavigation { get; set; }
}