// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quiz.Data;

public partial class Rooms
{
    public int Id_Room { get; set; }

    public int fk_User { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Password { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<RoomQuizes> RoomQuizes { get; set; } = new List<RoomQuizes>();

    public virtual Users fk_UserNavigation { get; set; }
}