// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quiz.Data;

public partial class Session
{
    public int Id_Session { get; set; }

    public int fk_Quiz { get; set; }

    public string User { get; set; }

    public int Score { get; set; }

    public DateTime Date { get; set; }

    public virtual Quizes fk_QuizNavigation { get; set; }
}