// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quiz.Data;

public partial class Users
{
    public int Id_User { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public bool Active { get; set; }

    public bool Login { get; set; }

    public virtual ICollection<Quizes> Quizes { get; set; } = new List<Quizes>();

    public virtual ICollection<Rooms> Rooms { get; set; } = new List<Rooms>();
}