CREATE DATABASE Quiz;
USE Quiz;

CREATE TABLE Users(
	Id_User INT NOT NULL IDENTITY CONSTRAINT PK_Users PRIMARY KEY,
	[Name] VARCHAR(MAX) NOT NULL,
	Email VARCHAR(MAX) NOT NULL,
	[Password] VARCHAR(MAX) NOT NULL,
	Active BIT NOT NULL DEFAULT 1,
	[Login] BIT NOT NULL DEFAULT 0,
);

CREATE TABLE Quizes(
	Id_Quiz INT NOT NULL IDENTITY CONSTRAINT PK_Quizes PRIMARY KEY,
	fk_User INT NOT NULL CONSTRAINT FK_Quizes_Users FOREIGN KEY REFERENCES Users(Id_User),
	[Name] VARCHAR(MAX) NOT NULL,
	[Description] VARCHAR(MAX) NOT NULL,
	Active BIT NOT NULL DEFAULT 1,
);

CREATE TABLE Questions(
	Id_Question INT NOT NULL IDENTITY CONSTRAINT PK_Questions PRIMARY KEY,
	fk_Quiz INT NOT NULL CONSTRAINT FK_Questions_Quizes FOREIGN KEY REFERENCES Quizes(Id_Quiz),
	[Description] VARCHAR(MAX) NOT NULL,
);

CREATE TABLE Answers(
	Id_Answer INT NOT NULL IDENTITY CONSTRAINT PK_Answers PRIMARY KEY,
	fk_Question INT NOT NULL CONSTRAINT FK_Answers_Questions FOREIGN KEY REFERENCES Questions(Id_Question),
	[Description] VARCHAR(MAX) NOT NULL,
	IsCorrect BIT NOT NULL DEFAULT 0,
);

CREATE TABLE Rooms(
	Id_Room INT NOT NULL IDENTITY CONSTRAINT PK_Rooms PRIMARY KEY,
	fk_User INT NOT NULL CONSTRAINT FK_Rooms_Users FOREIGN KEY REFERENCES Users(Id_User),
	[Name] VARCHAR(MAX) NOT NULL,
	[Description] VARCHAR(MAX) NOT NULL,
	[Password] VARCHAR(MAX) NOT NULL,
	Active BIT NOT NULL DEFAULT 1,
);

CREATE TABLE RoomQuizes(
	Id_RoomQuize INT NOT NULL IDENTITY CONSTRAINT PK_RoomQuizes PRIMARY KEY,
	fk_Room INT NOT NULL CONSTRAINT FK_RoomQuizes_Rooms FOREIGN KEY REFERENCES Rooms(Id_Room),
	fk_Quiz INT NOT NULL CONSTRAINT FK_RoomQuizes_Quizes FOREIGN KEY REFERENCES Quizes(Id_Quiz),
);